{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  {{- if .Values.secretProviderClass.syncSecret.enabled }}
  secretObjects:
    - secretName: {{ .Values.secretProviderClass.syncSecret.name | quote }}
      type: Opaque
      data:
        - objectName: {{ .Values.secretProviderClass.objects.dbPasswordSecretName | quote }}
          key: {{ .Values.secretProviderClass.syncSecret.keys.PAYMENT_DB_PASSWORD | quote }}
        - objectName: {{ .Values.secretProviderClass.objects.apiKeySecretName | quote }}
          key: {{ .Values.secretProviderClass.syncSecret.keys.PAYMENT_API_KEY | quote }}
  {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    {{- if .Values.workloadIdentity.enabled }}
    useWorkloadIdentity: "true"
    {{- end }}
    clientID: {{ .Values.secretProviderClass.clientID | quote }}
    keyvaultName: {{ .Values.secretProviderClass.kvname | quote }}
    tenantId: {{ .Values.secretProviderClass.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.secretProviderClass.objects.dbPasswordSecretName }}
          objectType: secret
        - |
          objectName: {{ .Values.secretProviderClass.objects.apiKeySecretName }}
          objectType: secret
{{- end }}
