{{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "payment-api.fullname" . }}-spc
  labels:
    {{- include "payment-api.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ include "payment-api.fullname" . }}-secrets
    type: Opaque
    data:
    - objectName: db-connection-string
      key: DB_CONNECTION_STRING
    - objectName: payment-api-key
      key: PAYMENT_API_KEY
      
{{- end}}
