apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment-api.fullname" . }}-service
  labels:
    {{- include "payment-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "payment-api.selector" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
