{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "payment-worker.fullname" . }}-np
  labels:
    {{- include "payment-worker.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "payment-worker.selector" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
        {{- range .Values.networkPolicy.ingress.allowedNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
        {{- end }}
        {{- range .Values.networkPolicy.ingress.allowedCidrs }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
      ports:
        - port: {{ .Values.deployment.containerPort }}
          protocol: TCP
  egress:
    {{- if .Values.networkPolicy.egress.allowDns }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- end }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
    {{- range .Values.networkPolicy.egress.allowedNamespaces }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
    {{- end }}
    {{- range .Values.networkPolicy.egress.allowedCidrs }}
    - to:
        - ipBlock:
            cidr: {{ . | quote }}
    {{- end }}
{{- end }}
