apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "payment-worker.fullname" . }}-pvc
  labels:
    {{- include "payment-worker.labels" . | nindent 4 }}
spec:
  {{- if .Values.storageClass.name }}
  storageClassName: {{ .Values.storageClass.name | quote }}
  {{- end }}
  accessModes:
  {{- range .Values.storageClass.accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storageClass.size }}
