apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment-worker.fullname" . }}-service
  labels:
    {{- include "payment-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8090
      name: http
