name: GCP-infra (01-cloudrun)

on:
  pull_request:
    paths:
      - "cloud-projects/01-cloudrun/**"
      - ".github/workflows/terraform.yml"
  push:
    branches: [main]
    paths:
      - "cloud-projects/01-cloudrun/**"
      - ".github/workflows/terraform.yml"
  # workflow_dispatch:
  #   inputs:
  #     apply:
  #       description: 'Build + apply?'
  #       type: boolean
  #       default: true

env:
  GOOGLE_PROJECT: ${{ vars.GCP_PROJECT_ID }}
  TF_VAR_image: europe-central2-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/repo01/flask-app:${{ github.sha }}

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: cloud-projects/01-cloudrun/infra

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.SA_PLAN }}
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -input=false -var-file=dev.tfvars

  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cloud-projects/01-cloudrun
    steps:
      - uses: actions/checkout@v4
      - name: Show OIDC claims
        run: |
          curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=test" \
              | jq -r '.value | split(".")[1] | @base64d | fromjson | {sub, ref, event_name, job_workflow_ref}'
      - name: Build image
        run: docker build --platform linux/amd64 -t "$TF_VAR_image" .
      - uses: google-github-actions/auth@v2
        id: registry_auth
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          token_format: access_token
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.SA_APPLY }}
      - name: Docker auth
        uses: docker/login-action@v3
        with:
          registry: europe-central2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.registry_auth.outputs.access_token }}
      - name: Push image
        run: docker push "$TF_VAR_image"

  apply:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.SA_APPLY }}
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform apply -auto-approve -input=false -var-file=dev.tfvars
